use sc_24K_bigdata31_p2_2;

SELECT DATABASE();

SHOW TABLES;

select * from COMPLAIN_TABLE;

select * from COMMENT_TABLE;

INSERT INTO COMMENT_TABLE(CPL_IDX,CMT_CONTENT,CMT_DT,ADMIN_ID) VALUES(45,"나는 내가 빛나는 별인줄 알았어요","2024-01-01 00:00:00","admin")

INSERT INTO ADMIN_TABLE(ID, PW, NAME) VALUES("admin","1234","관리자1");

SHOW COLUMNS FROM ADMIN_TABLE;

SHOW COLUMNS FROM COMMENT_TABLE;
commit;
